### ISSUE TITLE
Menu navigation not working

### ISSUE THREAD

**Issue by peter-sc** [funkydan2/alpha-church#4] opened 2018-09-21 20:27 UTC
Hello, when the site is deployed locally, there is a problem while navigating through menus. 

1. Press Home
2. Press Contact
3. Press About - the link to open is localhost:1313/contact/menu and you get 404

**Comment by funkydan2** [comment] 2018-09-21 21:08
Thanks, @peter-sc. 

This was caused by the exampleSite using relative URLs rather than absolute in that menu item.

[I've committed a fix it now](https://github.com/funkydan2/alpha-church/commit/47f84265db2f72adaf4058a783f6eb7514ef37fa). The updates will be reflected on [the Hugo themes preview](https://themes.gohugo.io//theme/alpha-church/) when they do their next update.

**Closed by funkydan2** 2018-09-21 21:08 UTC
