### ISSUE TITLE
Can i set up the comment below the article?

### ISSUE THREAD

**Issue by Gan-Jason** [funkydan2/alpha-church#14] opened 2019-07-26 08:50 UTC
Hi,i want to open the commet such like github issue,is it possible?And,can i change the map which show at home page to a static picture in my static folder?

**Comment by funkydan2** [comment] 2019-07-26 11:07
Hi @Gan-Jason, thanks for your questions.

From what I can see you've got two requests:
1. Implementing a commenting system for blog/podcast, etc.?
2. An option to replace the map with a picture?

Is that right?

Neither of these are things I've thought about, and I wasn't thinking of implementing them. However,
1. This is possible. In the [hugo docs there's a list of commenting systems which can be implemented](https://gohugo.io/content-management/comments/). Do you have a preference? (Disqus would be the quickest to implement.)
2. Would be easy to do—in fact [the design I based this theme off has that](https://html5up.net/alpha). It's something I might be able to do in the next few weeks.

Though, if you've got some programming skills, you could fork the project and implement these yourself. And if you wanted to send in a Push Request, I'd be pleased to review the code and include it in the main repo.

**Comment by Gan-Jason** [comment] 2019-07-27 11:20
> Hi @Gan-Jason, thanks for your questions.
> 
> From what I can see you've got two requests:
> 
> 1. Implementing a commenting system for blog/podcast, etc.?
> 2. An option to replace the map with a picture?
> 
> Is that right?
> 
> Neither of these are things I've thought about, and I wasn't thinking of implementing them. However,
> 
> 1. This is possible. In the [hugo docs there's a list of commenting systems which can be implemented](https://gohugo.io/content-management/comments/). Do you have a preference? (Disqus would be the quickest to implement.)
> 2. Would be easy to do—in fact [the design I based this theme off has that](https://html5up.net/alpha). It's something I might be able to do in the next few weeks.
> 
> Though, if you've got some programming skills, you could fork the project and implement these yourself. And if you wanted to send in a Push Request, I'd be pleased to review the code and include it in the main repo.

Thanks for reply me patiently so much，i figured out these problem with your guide.The second problem that i add a ‘p' label in the index.html to resolve it.I'm sry to bother you again,i deploy my site on my server afterwards,the navigation on the top doesn't work,it cannot be pull down auto or  by clicking,such like static text:
![image](https://user-images.githubusercontent.com/48959194/61993777-86d87000-b0a3-11e9-8567-f57884634c84.png)

**Comment by funkydan2** [comment] 2019-07-27 11:32
Hi @Gan-Jason,

I found your site's code in your github repository and had a look at it. When I opened up the site in Firefox and looked at the developer tools console, there was a few errors:

![Screen Shot 2019-07-27 at 9 26 02 pm](https://user-images.githubusercontent.com/10623666/61993837-2fdb9680-b0b5-11e9-9783-86fcf82af835.png)

The problem is to do with the SRI resource checking that the theme uses, and so the jquery library isn't being loaded. Is your public server doing any transformation of the assets when it deploys?

**Comment by Gan-Jason** [comment] 2019-07-27 11:56
Actually i don‘t know about jQuery,how can i check is the server's transformation?

**Comment by funkydan2** [comment] 2019-07-27 12:34
There's something wonky with the hash-sum being given for your javascript resources.

Have a look at https://github.com/Gan-Jason/Gan-Blog/blob/36e38fd10b15d0297a2a3b56ada3904545f49d8f/index.html#L283

For some reason the `+` characters which should be in the SRI checks have been replaced by `&#43;`.

**Comment by Gan-Jason** [comment] 2019-07-27 15:54
> There's something wonky with the hash-sum encoding for your javascript resources.
> 
> Have a look at https://github.com/Gan-Jason/Gan-Blog/blob/36e38fd10b15d0297a2a3b56ada3904545f49d8f/index.html#L283
> 
> For some reason the `+` characters which should be in the SRI checks have been replaced by `&#43;`.

It had became replaced by &#43 since i used ```hugo``` to build it ,i tried to replace it by myself but it stay the same.

**Comment by Gan-Jason** [comment] 2019-07-27 17:19
> There's something wonky with the hash-sum encoding for your javascript resources.
> 
> Have a look at https://github.com/Gan-Jason/Gan-Blog/blob/36e38fd10b15d0297a2a3b56ada3904545f49d8f/index.html#L283
> 
> For some reason the `+` characters which should be in the SRI checks have been replaced by `&#43;`.

Thanks for your help,i've resolved it by doing the same follow the  [similar issue](https://github.com/miguelcobain/ember-paper/issues/224) answer,it  ended up adding the empty integrity tag to every script tag.

**Comment by funkydan2** [comment] 2019-07-27 22:12
I'm not sure what's happening.

What operating system and version of hugo are you using to build the site (what's the output of `hugo version`? How are you uploading/pushing the code to GitHub? How is it deployed to your website?

I've not seen characters get encoded that way in the integrity check previously, so I'm wondering where the problem is coming from?

**Comment by Gan-Jason** [comment] 2019-07-28 03:37
Hi,funky.My pc:windows10  
hugo:Hugo Static Site Generator v0.55.6/extended windows/amd64  
Build command:hugo
Then ```cd``` into public folder  build just now,```git add .```,```git commit...```,```git push```,to push to Github.   
In my server:i use the nginx and this is my configure file:  
![image](https://user-images.githubusercontent.com/48959194/62001843-001ba580-b12c-11e9-8f16-b4f62f4ea668.png)

**Comment by Gan-Jason** [comment] 2019-07-28 04:45
I tried to add a null integrity script behind each script,like this:  
![image](https://user-images.githubusercontent.com/48959194/62002383-7bce2000-b135-11e9-85f7-9867a60eb5c4.png)
and it did work for some page,but not all page

**Comment by funkydan2** [comment] 2019-07-28 06:40
When you run `hugo server` does the dropdown menu work? Can you check the page source when running the test server and see if the integrity values are correct?

**Comment by Gan-Jason** [comment] 2019-07-28 07:34
> When you run `hugo server` does the dropdown menu work? Can you check the page source when running the test server and see if the integrity values are correct?

yes,it did work in local test,and also the wrong integrity ,i checked it for several times.But there is a surpricing news,it seem to run normally for the reason that i guess is adding those null integrity script

**Comment by funkydan2** [comment] 2019-07-28 07:44
Great - well if it's working don't change anything! 

Though I'm still confused as to how the integrity values are being changed. It'd be worth seeing if the values are correct when they're built by `hugo` (i.e. are they correct in the files in your `/public` directory, and if not, why not.

**Comment by Gan-Jason** [comment] 2019-07-28 08:41
Thanks for your help!The value are not correct in my ```/public``` ,Anyway,the theme is fabulous,good job

**Comment by funkydan2** [comment] 2019-07-28 08:50
Great, well I'll close this issue then. If you have any other problems with Hugo, can I recommend the [Hugo Discourse Forum](https://discourse.gohugo.io). I'm actively involved over there, and there's lots of other great help too.

**Closed by funkydan2** 2019-07-28 08:50 UTC
Labels: enhancement
